title: str = "The Shadows Of War"
chunk_width = 16
chunk_height = 9
chunk_dimensions = chunk_width, chunk_height
fps: int = 60
pixel_size: int = 3
tile_size: int = 16*pixel_size
window_width: int = chunk_width*tile_size
window_height: int = chunk_height*tile_size
window_dimensions = window_width, window_height
tick: int = 0